### ISSUE TITLE
Latest Rake fails on pinnned version of Rubocop

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#1106]
I encountered this error locally this morning, while working on #1105, using new rake `12.0.0` and pinned rubocop `0.35.1`.

```sh
$ bundle update
Fetching https://github.com/GoogleCloudPlatform/google-cloud-ruby.git
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Installing rake 12.0.0 (was 11.3.0)
...
Using rubocop 0.35.1
...


$ bundle exec rake ci
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007f9cbbc17140>
/Users/quartzmo/.rbenv/versions/2.3.1/gemsets/gcloud-ruby-yard/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:23:in `initialize'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-datastore/Rakefile:5:in `new'
/Users/quartzmo/code/google/codez/gcloud-ruby/google-cloud-datastore/Rakefile:5:in `<top (required)>'
/Users/quartzmo/.rbenv/versions/2.3.1/gemsets/gcloud-ruby-yard/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
```

Gem
